/*
  qt-core-constants.cc
  
  Qore Programming Language

  Copyright 2003 - 2009 David Nichols

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "qt-core.h"

DLLLOCAL void add_core_constants(QoreNamespace &qt_ns) {
   // CheckState enum
   qt_ns.addConstant("Unchecked",                new QoreBigIntNode(Qt::Unchecked));
   qt_ns.addConstant("PartiallyChecked",         new QoreBigIntNode(Qt::PartiallyChecked));
   qt_ns.addConstant("Checked",                  new QoreBigIntNode(Qt::Checked));

   // orientation enum values
   qt_ns.addConstant("Vertical",        new QoreBigIntNode(Qt::Vertical));
   qt_ns.addConstant("Horizontal",      new QoreBigIntNode(Qt::Horizontal));

   // GlobalColor enum
   qt_ns.addConstant("color0",            new QoreBigIntNode(Qt::color0));
   qt_ns.addConstant("color1",            new QoreBigIntNode(Qt::color1));
   qt_ns.addConstant("black",             new QoreBigIntNode(Qt::black));
   qt_ns.addConstant("white",             new QoreBigIntNode(Qt::white));
   qt_ns.addConstant("darkGray",          new QoreBigIntNode(Qt::darkGray));
   qt_ns.addConstant("gray",              new QoreBigIntNode(Qt::gray));
   qt_ns.addConstant("lightGray",         new QoreBigIntNode(Qt::lightGray));
   qt_ns.addConstant("red",               new QoreBigIntNode(Qt::red));
   qt_ns.addConstant("green",             new QoreBigIntNode(Qt::green));
   qt_ns.addConstant("blue",              new QoreBigIntNode(Qt::blue));
   qt_ns.addConstant("cyan",              new QoreBigIntNode(Qt::cyan));
   qt_ns.addConstant("magenta",           new QoreBigIntNode(Qt::magenta));
   qt_ns.addConstant("yellow",            new QoreBigIntNode(Qt::yellow));
   qt_ns.addConstant("darkRed",           new QoreBigIntNode(Qt::darkRed));
   qt_ns.addConstant("darkGreen",         new QoreBigIntNode(Qt::darkGreen));
   qt_ns.addConstant("darkBlue",          new QoreBigIntNode(Qt::darkBlue));
   qt_ns.addConstant("darkCyan",          new QoreBigIntNode(Qt::darkCyan));
   qt_ns.addConstant("darkMagenta",       new QoreBigIntNode(Qt::darkMagenta));
   qt_ns.addConstant("darkYellow",        new QoreBigIntNode(Qt::darkYellow));
   qt_ns.addConstant("transparent",       new QoreBigIntNode(Qt::transparent));

   // BrushStyle enum
   qt_ns.addConstant("NoBrush",                  new BrushStyleNode(Qt::NoBrush));
   qt_ns.addConstant("SolidPattern",             new BrushStyleNode(Qt::SolidPattern));
   qt_ns.addConstant("Dense1Pattern",            new BrushStyleNode(Qt::Dense1Pattern));
   qt_ns.addConstant("Dense2Pattern",            new BrushStyleNode(Qt::Dense2Pattern));
   qt_ns.addConstant("Dense3Pattern",            new BrushStyleNode(Qt::Dense3Pattern));
   qt_ns.addConstant("Dense4Pattern",            new BrushStyleNode(Qt::Dense4Pattern));
   qt_ns.addConstant("Dense5Pattern",            new BrushStyleNode(Qt::Dense5Pattern));
   qt_ns.addConstant("Dense6Pattern",            new BrushStyleNode(Qt::Dense6Pattern));
   qt_ns.addConstant("Dense7Pattern",            new BrushStyleNode(Qt::Dense7Pattern));
   qt_ns.addConstant("HorPattern",               new BrushStyleNode(Qt::HorPattern));
   qt_ns.addConstant("VerPattern",               new BrushStyleNode(Qt::VerPattern));
   qt_ns.addConstant("CrossPattern",             new BrushStyleNode(Qt::CrossPattern));
   qt_ns.addConstant("BDiagPattern",             new BrushStyleNode(Qt::BDiagPattern));
   qt_ns.addConstant("FDiagPattern",             new BrushStyleNode(Qt::FDiagPattern));
   qt_ns.addConstant("DiagCrossPattern",         new BrushStyleNode(Qt::DiagCrossPattern));
   qt_ns.addConstant("LinearGradientPattern",    new BrushStyleNode(Qt::LinearGradientPattern));
   qt_ns.addConstant("RadialGradientPattern",    new BrushStyleNode(Qt::RadialGradientPattern));
   qt_ns.addConstant("ConicalGradientPattern",   new BrushStyleNode(Qt::ConicalGradientPattern));
   qt_ns.addConstant("TexturePattern",           new BrushStyleNode(Qt::TexturePattern));

   // PenStyle enum
   qt_ns.addConstant("NoPen",             new PenStyleNode(Qt::NoPen));
   qt_ns.addConstant("SolidLine",         new PenStyleNode(Qt::SolidLine));
   qt_ns.addConstant("DashLine",          new PenStyleNode(Qt::DashLine));
   qt_ns.addConstant("DotLine",           new PenStyleNode(Qt::DotLine));
   qt_ns.addConstant("DashDotLine",       new PenStyleNode(Qt::DashDotLine));
   qt_ns.addConstant("DashDotDotLine",    new PenStyleNode(Qt::DashDotDotLine));
   qt_ns.addConstant("CustomDashLine",    new PenStyleNode(Qt::CustomDashLine));

   // AlignmentFlag enum
   qt_ns.addConstant("AlignLeft",                new QoreBigIntNode(Qt::AlignLeft));
   qt_ns.addConstant("AlignLeading",             new QoreBigIntNode(Qt::AlignLeading));
   qt_ns.addConstant("AlignRight",               new QoreBigIntNode(Qt::AlignRight));
   qt_ns.addConstant("AlignTrailing",            new QoreBigIntNode(Qt::AlignTrailing));
   qt_ns.addConstant("AlignHCenter",             new QoreBigIntNode(Qt::AlignHCenter));
   qt_ns.addConstant("AlignJustify",             new QoreBigIntNode(Qt::AlignJustify));
   qt_ns.addConstant("AlignAbsolute",            new QoreBigIntNode(Qt::AlignAbsolute));
   qt_ns.addConstant("AlignHorizontal_Mask",     new QoreBigIntNode(Qt::AlignHorizontal_Mask));
   qt_ns.addConstant("AlignTop",                 new QoreBigIntNode(Qt::AlignTop));
   qt_ns.addConstant("AlignBottom",              new QoreBigIntNode(Qt::AlignBottom));
   qt_ns.addConstant("AlignVCenter",             new QoreBigIntNode(Qt::AlignVCenter));
   qt_ns.addConstant("AlignVertical_Mask",       new QoreBigIntNode(Qt::AlignVertical_Mask));
   qt_ns.addConstant("AlignCenter",              new QoreBigIntNode(Qt::AlignCenter));

   // MouseButton enum
   qt_ns.addConstant("NoButton",                 new QoreBigIntNode(Qt::NoButton));
   qt_ns.addConstant("LeftButton",               new QoreBigIntNode(Qt::LeftButton));
   qt_ns.addConstant("RightButton",              new QoreBigIntNode(Qt::RightButton));
   qt_ns.addConstant("MidButton",                new QoreBigIntNode(Qt::MidButton));
   qt_ns.addConstant("XButton1",                 new QoreBigIntNode(Qt::XButton1));
   qt_ns.addConstant("XButton2",                 new QoreBigIntNode(Qt::XButton2));
   qt_ns.addConstant("MouseButtonMask",          new QoreBigIntNode(Qt::MouseButtonMask));

   // Modifier enum
   qt_ns.addConstant("META",                     new QoreBigIntNode(Qt::META));
   qt_ns.addConstant("SHIFT",                    new QoreBigIntNode(Qt::SHIFT));
   qt_ns.addConstant("CTRL",                     new QoreBigIntNode(Qt::CTRL));
   qt_ns.addConstant("ALT",                      new QoreBigIntNode(Qt::ALT));
   qt_ns.addConstant("MODIFIER_MASK",            new QoreBigIntNode(Qt::MODIFIER_MASK));
   qt_ns.addConstant("UNICODE_ACCEL",            new QoreBigIntNode(Qt::UNICODE_ACCEL));

   // DayOfWeek
   qt_ns.addConstant("Monday",                   new QoreBigIntNode(Qt::Monday));
   qt_ns.addConstant("Tuesday",                  new QoreBigIntNode(Qt::Tuesday));
   qt_ns.addConstant("Wednesday",                new QoreBigIntNode(Qt::Wednesday));
   qt_ns.addConstant("Thursday",                 new QoreBigIntNode(Qt::Thursday));
   qt_ns.addConstant("Friday",                   new QoreBigIntNode(Qt::Friday));
   qt_ns.addConstant("Saturday",                 new QoreBigIntNode(Qt::Saturday));
   qt_ns.addConstant("Sunday",                   new QoreBigIntNode(Qt::Sunday));

   // ContextMenuPolicy enum
   qt_ns.addConstant("NoContextMenu",            new QoreBigIntNode(Qt::NoContextMenu));
   qt_ns.addConstant("DefaultContextMenu",       new QoreBigIntNode(Qt::DefaultContextMenu));
   qt_ns.addConstant("ActionsContextMenu",       new QoreBigIntNode(Qt::ActionsContextMenu));
   qt_ns.addConstant("CustomContextMenu",        new QoreBigIntNode(Qt::CustomContextMenu));
   qt_ns.addConstant("PreventContextMenu",       new QoreBigIntNode(Qt::PreventContextMenu));

   // Key enum
   qt_ns.addConstant("Key_Escape",               new QoreBigIntNode(Qt::Key_Escape));
   qt_ns.addConstant("Key_Tab",                  new QoreBigIntNode(Qt::Key_Tab));
   qt_ns.addConstant("Key_Backtab",              new QoreBigIntNode(Qt::Key_Backtab));
   qt_ns.addConstant("Key_Backspace",            new QoreBigIntNode(Qt::Key_Backspace));
   qt_ns.addConstant("Key_Return",               new QoreBigIntNode(Qt::Key_Return));
   qt_ns.addConstant("Key_Enter",                new QoreBigIntNode(Qt::Key_Enter));
   qt_ns.addConstant("Key_Insert",               new QoreBigIntNode(Qt::Key_Insert));
   qt_ns.addConstant("Key_Delete",               new QoreBigIntNode(Qt::Key_Delete));
   qt_ns.addConstant("Key_Pause",                new QoreBigIntNode(Qt::Key_Pause));
   qt_ns.addConstant("Key_Print",                new QoreBigIntNode(Qt::Key_Print));
   qt_ns.addConstant("Key_SysReq",               new QoreBigIntNode(Qt::Key_SysReq));
   qt_ns.addConstant("Key_Clear",                new QoreBigIntNode(Qt::Key_Clear));
   qt_ns.addConstant("Key_Home",                 new QoreBigIntNode(Qt::Key_Home));
   qt_ns.addConstant("Key_End",                  new QoreBigIntNode(Qt::Key_End));
   qt_ns.addConstant("Key_Left",                 new QoreBigIntNode(Qt::Key_Left));
   qt_ns.addConstant("Key_Up",                   new QoreBigIntNode(Qt::Key_Up));
   qt_ns.addConstant("Key_Right",                new QoreBigIntNode(Qt::Key_Right));
   qt_ns.addConstant("Key_Down",                 new QoreBigIntNode(Qt::Key_Down));
   qt_ns.addConstant("Key_PageUp",               new QoreBigIntNode(Qt::Key_PageUp));
   qt_ns.addConstant("Key_PageDown",             new QoreBigIntNode(Qt::Key_PageDown));
   qt_ns.addConstant("Key_Shift",                new QoreBigIntNode(Qt::Key_Shift));
   qt_ns.addConstant("Key_Control",              new QoreBigIntNode(Qt::Key_Control));
   qt_ns.addConstant("Key_Meta",                 new QoreBigIntNode(Qt::Key_Meta));
   qt_ns.addConstant("Key_Alt",                  new QoreBigIntNode(Qt::Key_Alt));
   qt_ns.addConstant("Key_CapsLock",             new QoreBigIntNode(Qt::Key_CapsLock));
   qt_ns.addConstant("Key_NumLock",              new QoreBigIntNode(Qt::Key_NumLock));
   qt_ns.addConstant("Key_ScrollLock",           new QoreBigIntNode(Qt::Key_ScrollLock));
   qt_ns.addConstant("Key_F1",                   new QoreBigIntNode(Qt::Key_F1));
   qt_ns.addConstant("Key_F2",                   new QoreBigIntNode(Qt::Key_F2));
   qt_ns.addConstant("Key_F3",                   new QoreBigIntNode(Qt::Key_F3));
   qt_ns.addConstant("Key_F4",                   new QoreBigIntNode(Qt::Key_F4));
   qt_ns.addConstant("Key_F5",                   new QoreBigIntNode(Qt::Key_F5));
   qt_ns.addConstant("Key_F6",                   new QoreBigIntNode(Qt::Key_F6));
   qt_ns.addConstant("Key_F7",                   new QoreBigIntNode(Qt::Key_F7));
   qt_ns.addConstant("Key_F8",                   new QoreBigIntNode(Qt::Key_F8));
   qt_ns.addConstant("Key_F9",                   new QoreBigIntNode(Qt::Key_F9));
   qt_ns.addConstant("Key_F10",                  new QoreBigIntNode(Qt::Key_F10));
   qt_ns.addConstant("Key_F11",                  new QoreBigIntNode(Qt::Key_F11));
   qt_ns.addConstant("Key_F12",                  new QoreBigIntNode(Qt::Key_F12));
   qt_ns.addConstant("Key_F13",                  new QoreBigIntNode(Qt::Key_F13));
   qt_ns.addConstant("Key_F14",                  new QoreBigIntNode(Qt::Key_F14));
   qt_ns.addConstant("Key_F15",                  new QoreBigIntNode(Qt::Key_F15));
   qt_ns.addConstant("Key_F16",                  new QoreBigIntNode(Qt::Key_F16));
   qt_ns.addConstant("Key_F17",                  new QoreBigIntNode(Qt::Key_F17));
   qt_ns.addConstant("Key_F18",                  new QoreBigIntNode(Qt::Key_F18));
   qt_ns.addConstant("Key_F19",                  new QoreBigIntNode(Qt::Key_F19));
   qt_ns.addConstant("Key_F20",                  new QoreBigIntNode(Qt::Key_F20));
   qt_ns.addConstant("Key_F21",                  new QoreBigIntNode(Qt::Key_F21));
   qt_ns.addConstant("Key_F22",                  new QoreBigIntNode(Qt::Key_F22));
   qt_ns.addConstant("Key_F23",                  new QoreBigIntNode(Qt::Key_F23));
   qt_ns.addConstant("Key_F24",                  new QoreBigIntNode(Qt::Key_F24));
   qt_ns.addConstant("Key_F25",                  new QoreBigIntNode(Qt::Key_F25));
   qt_ns.addConstant("Key_F26",                  new QoreBigIntNode(Qt::Key_F26));
   qt_ns.addConstant("Key_F27",                  new QoreBigIntNode(Qt::Key_F27));
   qt_ns.addConstant("Key_F28",                  new QoreBigIntNode(Qt::Key_F28));
   qt_ns.addConstant("Key_F29",                  new QoreBigIntNode(Qt::Key_F29));
   qt_ns.addConstant("Key_F30",                  new QoreBigIntNode(Qt::Key_F30));
   qt_ns.addConstant("Key_F31",                  new QoreBigIntNode(Qt::Key_F31));
   qt_ns.addConstant("Key_F32",                  new QoreBigIntNode(Qt::Key_F32));
   qt_ns.addConstant("Key_F33",                  new QoreBigIntNode(Qt::Key_F33));
   qt_ns.addConstant("Key_F34",                  new QoreBigIntNode(Qt::Key_F34));
   qt_ns.addConstant("Key_F35",                  new QoreBigIntNode(Qt::Key_F35));
   qt_ns.addConstant("Key_Super_L",              new QoreBigIntNode(Qt::Key_Super_L));
   qt_ns.addConstant("Key_Super_R",              new QoreBigIntNode(Qt::Key_Super_R));
   qt_ns.addConstant("Key_Menu",                 new QoreBigIntNode(Qt::Key_Menu));
   qt_ns.addConstant("Key_Hyper_L",              new QoreBigIntNode(Qt::Key_Hyper_L));
   qt_ns.addConstant("Key_Hyper_R",              new QoreBigIntNode(Qt::Key_Hyper_R));
   qt_ns.addConstant("Key_Help",                 new QoreBigIntNode(Qt::Key_Help));
   qt_ns.addConstant("Key_Direction_L",          new QoreBigIntNode(Qt::Key_Direction_L));
   qt_ns.addConstant("Key_Direction_R",          new QoreBigIntNode(Qt::Key_Direction_R));
   qt_ns.addConstant("Key_Space",                new QoreBigIntNode(Qt::Key_Space));
   qt_ns.addConstant("Key_Any",                  new QoreBigIntNode(Qt::Key_Any));
   qt_ns.addConstant("Key_Exclam",               new QoreBigIntNode(Qt::Key_Exclam));
   qt_ns.addConstant("Key_QuoteDbl",             new QoreBigIntNode(Qt::Key_QuoteDbl));
   qt_ns.addConstant("Key_NumberSign",           new QoreBigIntNode(Qt::Key_NumberSign));
   qt_ns.addConstant("Key_Dollar",               new QoreBigIntNode(Qt::Key_Dollar));
   qt_ns.addConstant("Key_Percent",              new QoreBigIntNode(Qt::Key_Percent));
   qt_ns.addConstant("Key_Ampersand",            new QoreBigIntNode(Qt::Key_Ampersand));
   qt_ns.addConstant("Key_Apostrophe",           new QoreBigIntNode(Qt::Key_Apostrophe));
   qt_ns.addConstant("Key_ParenLeft",            new QoreBigIntNode(Qt::Key_ParenLeft));
   qt_ns.addConstant("Key_ParenRight",           new QoreBigIntNode(Qt::Key_ParenRight));
   qt_ns.addConstant("Key_Asterisk",             new QoreBigIntNode(Qt::Key_Asterisk));
   qt_ns.addConstant("Key_Plus",                 new QoreBigIntNode(Qt::Key_Plus));
   qt_ns.addConstant("Key_Comma",                new QoreBigIntNode(Qt::Key_Comma));
   qt_ns.addConstant("Key_Minus",                new QoreBigIntNode(Qt::Key_Minus));
   qt_ns.addConstant("Key_Period",               new QoreBigIntNode(Qt::Key_Period));
   qt_ns.addConstant("Key_Slash",                new QoreBigIntNode(Qt::Key_Slash));
   qt_ns.addConstant("Key_0",                    new QoreBigIntNode(Qt::Key_0));
   qt_ns.addConstant("Key_1",                    new QoreBigIntNode(Qt::Key_1));
   qt_ns.addConstant("Key_2",                    new QoreBigIntNode(Qt::Key_2));
   qt_ns.addConstant("Key_3",                    new QoreBigIntNode(Qt::Key_3));
   qt_ns.addConstant("Key_4",                    new QoreBigIntNode(Qt::Key_4));
   qt_ns.addConstant("Key_5",                    new QoreBigIntNode(Qt::Key_5));
   qt_ns.addConstant("Key_6",                    new QoreBigIntNode(Qt::Key_6));
   qt_ns.addConstant("Key_7",                    new QoreBigIntNode(Qt::Key_7));
   qt_ns.addConstant("Key_8",                    new QoreBigIntNode(Qt::Key_8));
   qt_ns.addConstant("Key_9",                    new QoreBigIntNode(Qt::Key_9));
   qt_ns.addConstant("Key_Colon",                new QoreBigIntNode(Qt::Key_Colon));
   qt_ns.addConstant("Key_Semicolon",            new QoreBigIntNode(Qt::Key_Semicolon));
   qt_ns.addConstant("Key_Less",                 new QoreBigIntNode(Qt::Key_Less));
   qt_ns.addConstant("Key_Equal",                new QoreBigIntNode(Qt::Key_Equal));
   qt_ns.addConstant("Key_Greater",              new QoreBigIntNode(Qt::Key_Greater));
   qt_ns.addConstant("Key_Question",             new QoreBigIntNode(Qt::Key_Question));
   qt_ns.addConstant("Key_At",                   new QoreBigIntNode(Qt::Key_At));
   qt_ns.addConstant("Key_A",                    new QoreBigIntNode(Qt::Key_A));
   qt_ns.addConstant("Key_B",                    new QoreBigIntNode(Qt::Key_B));
   qt_ns.addConstant("Key_C",                    new QoreBigIntNode(Qt::Key_C));
   qt_ns.addConstant("Key_D",                    new QoreBigIntNode(Qt::Key_D));
   qt_ns.addConstant("Key_E",                    new QoreBigIntNode(Qt::Key_E));
   qt_ns.addConstant("Key_F",                    new QoreBigIntNode(Qt::Key_F));
   qt_ns.addConstant("Key_G",                    new QoreBigIntNode(Qt::Key_G));
   qt_ns.addConstant("Key_H",                    new QoreBigIntNode(Qt::Key_H));
   qt_ns.addConstant("Key_I",                    new QoreBigIntNode(Qt::Key_I));
   qt_ns.addConstant("Key_J",                    new QoreBigIntNode(Qt::Key_J));
   qt_ns.addConstant("Key_K",                    new QoreBigIntNode(Qt::Key_K));
   qt_ns.addConstant("Key_L",                    new QoreBigIntNode(Qt::Key_L));
   qt_ns.addConstant("Key_M",                    new QoreBigIntNode(Qt::Key_M));
   qt_ns.addConstant("Key_N",                    new QoreBigIntNode(Qt::Key_N));
   qt_ns.addConstant("Key_O",                    new QoreBigIntNode(Qt::Key_O));
   qt_ns.addConstant("Key_P",                    new QoreBigIntNode(Qt::Key_P));
   qt_ns.addConstant("Key_Q",                    new QoreBigIntNode(Qt::Key_Q));
   qt_ns.addConstant("Key_R",                    new QoreBigIntNode(Qt::Key_R));
   qt_ns.addConstant("Key_S",                    new QoreBigIntNode(Qt::Key_S));
   qt_ns.addConstant("Key_T",                    new QoreBigIntNode(Qt::Key_T));
   qt_ns.addConstant("Key_U",                    new QoreBigIntNode(Qt::Key_U));
   qt_ns.addConstant("Key_V",                    new QoreBigIntNode(Qt::Key_V));
   qt_ns.addConstant("Key_W",                    new QoreBigIntNode(Qt::Key_W));
   qt_ns.addConstant("Key_X",                    new QoreBigIntNode(Qt::Key_X));
   qt_ns.addConstant("Key_Y",                    new QoreBigIntNode(Qt::Key_Y));
   qt_ns.addConstant("Key_Z",                    new QoreBigIntNode(Qt::Key_Z));
   qt_ns.addConstant("Key_BracketLeft",          new QoreBigIntNode(Qt::Key_BracketLeft));
   qt_ns.addConstant("Key_Backslash",            new QoreBigIntNode(Qt::Key_Backslash));
   qt_ns.addConstant("Key_BracketRight",         new QoreBigIntNode(Qt::Key_BracketRight));
   qt_ns.addConstant("Key_AsciiCircum",          new QoreBigIntNode(Qt::Key_AsciiCircum));
   qt_ns.addConstant("Key_Underscore",           new QoreBigIntNode(Qt::Key_Underscore));
   qt_ns.addConstant("Key_QuoteLeft",            new QoreBigIntNode(Qt::Key_QuoteLeft));
   qt_ns.addConstant("Key_BraceLeft",            new QoreBigIntNode(Qt::Key_BraceLeft));
   qt_ns.addConstant("Key_Bar",                  new QoreBigIntNode(Qt::Key_Bar));
   qt_ns.addConstant("Key_BraceRight",           new QoreBigIntNode(Qt::Key_BraceRight));
   qt_ns.addConstant("Key_AsciiTilde",           new QoreBigIntNode(Qt::Key_AsciiTilde));
   qt_ns.addConstant("Key_nobreakspace",         new QoreBigIntNode(Qt::Key_nobreakspace));
   qt_ns.addConstant("Key_exclamdown",           new QoreBigIntNode(Qt::Key_exclamdown));
   qt_ns.addConstant("Key_cent",                 new QoreBigIntNode(Qt::Key_cent));
   qt_ns.addConstant("Key_sterling",             new QoreBigIntNode(Qt::Key_sterling));
   qt_ns.addConstant("Key_currency",             new QoreBigIntNode(Qt::Key_currency));
   qt_ns.addConstant("Key_yen",                  new QoreBigIntNode(Qt::Key_yen));
   qt_ns.addConstant("Key_brokenbar",            new QoreBigIntNode(Qt::Key_brokenbar));
   qt_ns.addConstant("Key_section",              new QoreBigIntNode(Qt::Key_section));
   qt_ns.addConstant("Key_diaeresis",            new QoreBigIntNode(Qt::Key_diaeresis));
   qt_ns.addConstant("Key_copyright",            new QoreBigIntNode(Qt::Key_copyright));
   qt_ns.addConstant("Key_ordfeminine",          new QoreBigIntNode(Qt::Key_ordfeminine));
   qt_ns.addConstant("Key_guillemotleft",        new QoreBigIntNode(Qt::Key_guillemotleft));
   qt_ns.addConstant("Key_notsign",              new QoreBigIntNode(Qt::Key_notsign));
   qt_ns.addConstant("Key_hyphen",               new QoreBigIntNode(Qt::Key_hyphen));
   qt_ns.addConstant("Key_registered",           new QoreBigIntNode(Qt::Key_registered));
   qt_ns.addConstant("Key_macron",               new QoreBigIntNode(Qt::Key_macron));
   qt_ns.addConstant("Key_degree",               new QoreBigIntNode(Qt::Key_degree));
   qt_ns.addConstant("Key_plusminus",            new QoreBigIntNode(Qt::Key_plusminus));
   qt_ns.addConstant("Key_twosuperior",          new QoreBigIntNode(Qt::Key_twosuperior));
   qt_ns.addConstant("Key_threesuperior",        new QoreBigIntNode(Qt::Key_threesuperior));
   qt_ns.addConstant("Key_acute",                new QoreBigIntNode(Qt::Key_acute));
   qt_ns.addConstant("Key_mu",                   new QoreBigIntNode(Qt::Key_mu));
   qt_ns.addConstant("Key_paragraph",            new QoreBigIntNode(Qt::Key_paragraph));
   qt_ns.addConstant("Key_periodcentered",       new QoreBigIntNode(Qt::Key_periodcentered));
   qt_ns.addConstant("Key_cedilla",              new QoreBigIntNode(Qt::Key_cedilla));
   qt_ns.addConstant("Key_onesuperior",          new QoreBigIntNode(Qt::Key_onesuperior));
   qt_ns.addConstant("Key_masculine",            new QoreBigIntNode(Qt::Key_masculine));
   qt_ns.addConstant("Key_guillemotright",       new QoreBigIntNode(Qt::Key_guillemotright));
   qt_ns.addConstant("Key_onequarter",           new QoreBigIntNode(Qt::Key_onequarter));
   qt_ns.addConstant("Key_onehalf",              new QoreBigIntNode(Qt::Key_onehalf));
   qt_ns.addConstant("Key_threequarters",        new QoreBigIntNode(Qt::Key_threequarters));
   qt_ns.addConstant("Key_questiondown",         new QoreBigIntNode(Qt::Key_questiondown));
   qt_ns.addConstant("Key_Agrave",               new QoreBigIntNode(Qt::Key_Agrave));
   qt_ns.addConstant("Key_Aacute",               new QoreBigIntNode(Qt::Key_Aacute));
   qt_ns.addConstant("Key_Acircumflex",          new QoreBigIntNode(Qt::Key_Acircumflex));
   qt_ns.addConstant("Key_Atilde",               new QoreBigIntNode(Qt::Key_Atilde));
   qt_ns.addConstant("Key_Adiaeresis",           new QoreBigIntNode(Qt::Key_Adiaeresis));
   qt_ns.addConstant("Key_Aring",                new QoreBigIntNode(Qt::Key_Aring));
   qt_ns.addConstant("Key_AE",                   new QoreBigIntNode(Qt::Key_AE));
   qt_ns.addConstant("Key_Ccedilla",             new QoreBigIntNode(Qt::Key_Ccedilla));
   qt_ns.addConstant("Key_Egrave",               new QoreBigIntNode(Qt::Key_Egrave));
   qt_ns.addConstant("Key_Eacute",               new QoreBigIntNode(Qt::Key_Eacute));
   qt_ns.addConstant("Key_Ecircumflex",          new QoreBigIntNode(Qt::Key_Ecircumflex));
   qt_ns.addConstant("Key_Ediaeresis",           new QoreBigIntNode(Qt::Key_Ediaeresis));
   qt_ns.addConstant("Key_Igrave",               new QoreBigIntNode(Qt::Key_Igrave));
   qt_ns.addConstant("Key_Iacute",               new QoreBigIntNode(Qt::Key_Iacute));
   qt_ns.addConstant("Key_Icircumflex",          new QoreBigIntNode(Qt::Key_Icircumflex));
   qt_ns.addConstant("Key_Idiaeresis",           new QoreBigIntNode(Qt::Key_Idiaeresis));
   qt_ns.addConstant("Key_ETH",                  new QoreBigIntNode(Qt::Key_ETH));
   qt_ns.addConstant("Key_Ntilde",               new QoreBigIntNode(Qt::Key_Ntilde));
   qt_ns.addConstant("Key_Ograve",               new QoreBigIntNode(Qt::Key_Ograve));
   qt_ns.addConstant("Key_Oacute",               new QoreBigIntNode(Qt::Key_Oacute));
   qt_ns.addConstant("Key_Ocircumflex",          new QoreBigIntNode(Qt::Key_Ocircumflex));
   qt_ns.addConstant("Key_Otilde",               new QoreBigIntNode(Qt::Key_Otilde));
   qt_ns.addConstant("Key_Odiaeresis",           new QoreBigIntNode(Qt::Key_Odiaeresis));
   qt_ns.addConstant("Key_multiply",             new QoreBigIntNode(Qt::Key_multiply));
   qt_ns.addConstant("Key_Ooblique",             new QoreBigIntNode(Qt::Key_Ooblique));
   qt_ns.addConstant("Key_Ugrave",               new QoreBigIntNode(Qt::Key_Ugrave));
   qt_ns.addConstant("Key_Uacute",               new QoreBigIntNode(Qt::Key_Uacute));
   qt_ns.addConstant("Key_Ucircumflex",          new QoreBigIntNode(Qt::Key_Ucircumflex));
   qt_ns.addConstant("Key_Udiaeresis",           new QoreBigIntNode(Qt::Key_Udiaeresis));
   qt_ns.addConstant("Key_Yacute",               new QoreBigIntNode(Qt::Key_Yacute));
   qt_ns.addConstant("Key_THORN",                new QoreBigIntNode(Qt::Key_THORN));
   qt_ns.addConstant("Key_ssharp",               new QoreBigIntNode(Qt::Key_ssharp));
   qt_ns.addConstant("Key_division",             new QoreBigIntNode(Qt::Key_division));
   qt_ns.addConstant("Key_ydiaeresis",           new QoreBigIntNode(Qt::Key_ydiaeresis));
   qt_ns.addConstant("Key_AltGr",                new QoreBigIntNode(Qt::Key_AltGr));
   qt_ns.addConstant("Key_Multi_key",            new QoreBigIntNode(Qt::Key_Multi_key));
   qt_ns.addConstant("Key_Codeinput",            new QoreBigIntNode(Qt::Key_Codeinput));
   qt_ns.addConstant("Key_SingleCandidate",      new QoreBigIntNode(Qt::Key_SingleCandidate));
   qt_ns.addConstant("Key_MultipleCandidate",    new QoreBigIntNode(Qt::Key_MultipleCandidate));
   qt_ns.addConstant("Key_PreviousCandidate",    new QoreBigIntNode(Qt::Key_PreviousCandidate));
   qt_ns.addConstant("Key_Mode_switch",          new QoreBigIntNode(Qt::Key_Mode_switch));
   qt_ns.addConstant("Key_Kanji",                new QoreBigIntNode(Qt::Key_Kanji));
   qt_ns.addConstant("Key_Muhenkan",             new QoreBigIntNode(Qt::Key_Muhenkan));
   qt_ns.addConstant("Key_Henkan",               new QoreBigIntNode(Qt::Key_Henkan));
   qt_ns.addConstant("Key_Romaji",               new QoreBigIntNode(Qt::Key_Romaji));
   qt_ns.addConstant("Key_Hiragana",             new QoreBigIntNode(Qt::Key_Hiragana));
   qt_ns.addConstant("Key_Katakana",             new QoreBigIntNode(Qt::Key_Katakana));
   qt_ns.addConstant("Key_Hiragana_Katakana",    new QoreBigIntNode(Qt::Key_Hiragana_Katakana));
   qt_ns.addConstant("Key_Zenkaku",              new QoreBigIntNode(Qt::Key_Zenkaku));
   qt_ns.addConstant("Key_Hankaku",              new QoreBigIntNode(Qt::Key_Hankaku));
   qt_ns.addConstant("Key_Zenkaku_Hankaku",      new QoreBigIntNode(Qt::Key_Zenkaku_Hankaku));
   qt_ns.addConstant("Key_Touroku",              new QoreBigIntNode(Qt::Key_Touroku));
   qt_ns.addConstant("Key_Massyo",               new QoreBigIntNode(Qt::Key_Massyo));
   qt_ns.addConstant("Key_Kana_Lock",            new QoreBigIntNode(Qt::Key_Kana_Lock));
   qt_ns.addConstant("Key_Kana_Shift",           new QoreBigIntNode(Qt::Key_Kana_Shift));
   qt_ns.addConstant("Key_Eisu_Shift",           new QoreBigIntNode(Qt::Key_Eisu_Shift));
   qt_ns.addConstant("Key_Eisu_toggle",          new QoreBigIntNode(Qt::Key_Eisu_toggle));
   qt_ns.addConstant("Key_Hangul",               new QoreBigIntNode(Qt::Key_Hangul));
   qt_ns.addConstant("Key_Hangul_Start",         new QoreBigIntNode(Qt::Key_Hangul_Start));
   qt_ns.addConstant("Key_Hangul_End",           new QoreBigIntNode(Qt::Key_Hangul_End));
   qt_ns.addConstant("Key_Hangul_Hanja",         new QoreBigIntNode(Qt::Key_Hangul_Hanja));
   qt_ns.addConstant("Key_Hangul_Jamo",          new QoreBigIntNode(Qt::Key_Hangul_Jamo));
   qt_ns.addConstant("Key_Hangul_Romaja",        new QoreBigIntNode(Qt::Key_Hangul_Romaja));
   qt_ns.addConstant("Key_Hangul_Jeonja",        new QoreBigIntNode(Qt::Key_Hangul_Jeonja));
   qt_ns.addConstant("Key_Hangul_Banja",         new QoreBigIntNode(Qt::Key_Hangul_Banja));
   qt_ns.addConstant("Key_Hangul_PreHanja",      new QoreBigIntNode(Qt::Key_Hangul_PreHanja));
   qt_ns.addConstant("Key_Hangul_PostHanja",     new QoreBigIntNode(Qt::Key_Hangul_PostHanja));
   qt_ns.addConstant("Key_Hangul_Special",       new QoreBigIntNode(Qt::Key_Hangul_Special));
   qt_ns.addConstant("Key_Dead_Grave",           new QoreBigIntNode(Qt::Key_Dead_Grave));
   qt_ns.addConstant("Key_Dead_Acute",           new QoreBigIntNode(Qt::Key_Dead_Acute));
   qt_ns.addConstant("Key_Dead_Circumflex",      new QoreBigIntNode(Qt::Key_Dead_Circumflex));
   qt_ns.addConstant("Key_Dead_Tilde",           new QoreBigIntNode(Qt::Key_Dead_Tilde));
   qt_ns.addConstant("Key_Dead_Macron",          new QoreBigIntNode(Qt::Key_Dead_Macron));
   qt_ns.addConstant("Key_Dead_Breve",           new QoreBigIntNode(Qt::Key_Dead_Breve));
   qt_ns.addConstant("Key_Dead_Abovedot",        new QoreBigIntNode(Qt::Key_Dead_Abovedot));
   qt_ns.addConstant("Key_Dead_Diaeresis",       new QoreBigIntNode(Qt::Key_Dead_Diaeresis));
   qt_ns.addConstant("Key_Dead_Abovering",       new QoreBigIntNode(Qt::Key_Dead_Abovering));
   qt_ns.addConstant("Key_Dead_Doubleacute",     new QoreBigIntNode(Qt::Key_Dead_Doubleacute));
   qt_ns.addConstant("Key_Dead_Caron",           new QoreBigIntNode(Qt::Key_Dead_Caron));
   qt_ns.addConstant("Key_Dead_Cedilla",         new QoreBigIntNode(Qt::Key_Dead_Cedilla));
   qt_ns.addConstant("Key_Dead_Ogonek",          new QoreBigIntNode(Qt::Key_Dead_Ogonek));
   qt_ns.addConstant("Key_Dead_Iota",            new QoreBigIntNode(Qt::Key_Dead_Iota));
   qt_ns.addConstant("Key_Dead_Voiced_Sound",    new QoreBigIntNode(Qt::Key_Dead_Voiced_Sound));
   qt_ns.addConstant("Key_Dead_Semivoiced_Sound", new QoreBigIntNode(Qt::Key_Dead_Semivoiced_Sound));
   qt_ns.addConstant("Key_Dead_Belowdot",        new QoreBigIntNode(Qt::Key_Dead_Belowdot));
   qt_ns.addConstant("Key_Dead_Hook",            new QoreBigIntNode(Qt::Key_Dead_Hook));
   qt_ns.addConstant("Key_Dead_Horn",            new QoreBigIntNode(Qt::Key_Dead_Horn));
   qt_ns.addConstant("Key_Back",                 new QoreBigIntNode(Qt::Key_Back));
   qt_ns.addConstant("Key_Forward",              new QoreBigIntNode(Qt::Key_Forward));
   qt_ns.addConstant("Key_Stop",                 new QoreBigIntNode(Qt::Key_Stop));
   qt_ns.addConstant("Key_Refresh",              new QoreBigIntNode(Qt::Key_Refresh));
   qt_ns.addConstant("Key_VolumeDown",           new QoreBigIntNode(Qt::Key_VolumeDown));
   qt_ns.addConstant("Key_VolumeMute",           new QoreBigIntNode(Qt::Key_VolumeMute));
   qt_ns.addConstant("Key_VolumeUp",             new QoreBigIntNode(Qt::Key_VolumeUp));
   qt_ns.addConstant("Key_BassBoost",            new QoreBigIntNode(Qt::Key_BassBoost));
   qt_ns.addConstant("Key_BassUp",               new QoreBigIntNode(Qt::Key_BassUp));
   qt_ns.addConstant("Key_BassDown",             new QoreBigIntNode(Qt::Key_BassDown));
   qt_ns.addConstant("Key_TrebleUp",             new QoreBigIntNode(Qt::Key_TrebleUp));
   qt_ns.addConstant("Key_TrebleDown",           new QoreBigIntNode(Qt::Key_TrebleDown));
   qt_ns.addConstant("Key_MediaPlay",            new QoreBigIntNode(Qt::Key_MediaPlay));
   qt_ns.addConstant("Key_MediaStop",            new QoreBigIntNode(Qt::Key_MediaStop));
   qt_ns.addConstant("Key_MediaPrevious",        new QoreBigIntNode(Qt::Key_MediaPrevious));
   qt_ns.addConstant("Key_MediaNext",            new QoreBigIntNode(Qt::Key_MediaNext));
   qt_ns.addConstant("Key_MediaRecord",          new QoreBigIntNode(Qt::Key_MediaRecord));
   qt_ns.addConstant("Key_HomePage",             new QoreBigIntNode(Qt::Key_HomePage));
   qt_ns.addConstant("Key_Favorites",            new QoreBigIntNode(Qt::Key_Favorites));
   qt_ns.addConstant("Key_Search",               new QoreBigIntNode(Qt::Key_Search));
   qt_ns.addConstant("Key_Standby",              new QoreBigIntNode(Qt::Key_Standby));
   qt_ns.addConstant("Key_OpenUrl",              new QoreBigIntNode(Qt::Key_OpenUrl));
   qt_ns.addConstant("Key_LaunchMail",           new QoreBigIntNode(Qt::Key_LaunchMail));
   qt_ns.addConstant("Key_LaunchMedia",          new QoreBigIntNode(Qt::Key_LaunchMedia));
   qt_ns.addConstant("Key_Launch0",              new QoreBigIntNode(Qt::Key_Launch0));
   qt_ns.addConstant("Key_Launch1",              new QoreBigIntNode(Qt::Key_Launch1));
   qt_ns.addConstant("Key_Launch2",              new QoreBigIntNode(Qt::Key_Launch2));
   qt_ns.addConstant("Key_Launch3",              new QoreBigIntNode(Qt::Key_Launch3));
   qt_ns.addConstant("Key_Launch4",              new QoreBigIntNode(Qt::Key_Launch4));
   qt_ns.addConstant("Key_Launch5",              new QoreBigIntNode(Qt::Key_Launch5));
   qt_ns.addConstant("Key_Launch6",              new QoreBigIntNode(Qt::Key_Launch6));
   qt_ns.addConstant("Key_Launch7",              new QoreBigIntNode(Qt::Key_Launch7));
   qt_ns.addConstant("Key_Launch8",              new QoreBigIntNode(Qt::Key_Launch8));
   qt_ns.addConstant("Key_Launch9",              new QoreBigIntNode(Qt::Key_Launch9));
   qt_ns.addConstant("Key_LaunchA",              new QoreBigIntNode(Qt::Key_LaunchA));
   qt_ns.addConstant("Key_LaunchB",              new QoreBigIntNode(Qt::Key_LaunchB));
   qt_ns.addConstant("Key_LaunchC",              new QoreBigIntNode(Qt::Key_LaunchC));
   qt_ns.addConstant("Key_LaunchD",              new QoreBigIntNode(Qt::Key_LaunchD));
   qt_ns.addConstant("Key_LaunchE",              new QoreBigIntNode(Qt::Key_LaunchE));
   qt_ns.addConstant("Key_LaunchF",              new QoreBigIntNode(Qt::Key_LaunchF));
   qt_ns.addConstant("Key_MediaLast",            new QoreBigIntNode(Qt::Key_MediaLast));
   qt_ns.addConstant("Key_Select",               new QoreBigIntNode(Qt::Key_Select));
   qt_ns.addConstant("Key_Yes",                  new QoreBigIntNode(Qt::Key_Yes));
   qt_ns.addConstant("Key_No",                   new QoreBigIntNode(Qt::Key_No));
   qt_ns.addConstant("Key_Cancel",               new QoreBigIntNode(Qt::Key_Cancel));
   qt_ns.addConstant("Key_Printer",              new QoreBigIntNode(Qt::Key_Printer));
   qt_ns.addConstant("Key_Execute",              new QoreBigIntNode(Qt::Key_Execute));
   qt_ns.addConstant("Key_Sleep",                new QoreBigIntNode(Qt::Key_Sleep));
   qt_ns.addConstant("Key_Play",                 new QoreBigIntNode(Qt::Key_Play));
   qt_ns.addConstant("Key_Zoom",                 new QoreBigIntNode(Qt::Key_Zoom));
   qt_ns.addConstant("Key_Context1",             new QoreBigIntNode(Qt::Key_Context1));
   qt_ns.addConstant("Key_Context2",             new QoreBigIntNode(Qt::Key_Context2));
   qt_ns.addConstant("Key_Context3",             new QoreBigIntNode(Qt::Key_Context3));
   qt_ns.addConstant("Key_Context4",             new QoreBigIntNode(Qt::Key_Context4));
   qt_ns.addConstant("Key_Call",                 new QoreBigIntNode(Qt::Key_Call));
   qt_ns.addConstant("Key_Hangup",               new QoreBigIntNode(Qt::Key_Hangup));
   qt_ns.addConstant("Key_Flip",                 new QoreBigIntNode(Qt::Key_Flip));
   qt_ns.addConstant("Key_unknown",              new QoreBigIntNode(Qt::Key_unknown));

   // MatchFlag enum
   qt_ns.addConstant("MatchExactly",             new QoreBigIntNode(Qt::MatchExactly));
   qt_ns.addConstant("MatchContains",            new QoreBigIntNode(Qt::MatchContains));
   qt_ns.addConstant("MatchStartsWith",          new QoreBigIntNode(Qt::MatchStartsWith));
   qt_ns.addConstant("MatchEndsWith",            new QoreBigIntNode(Qt::MatchEndsWith));
   qt_ns.addConstant("MatchRegExp",              new QoreBigIntNode(Qt::MatchRegExp));
   qt_ns.addConstant("MatchWildcard",            new QoreBigIntNode(Qt::MatchWildcard));
   qt_ns.addConstant("MatchFixedString",         new QoreBigIntNode(Qt::MatchFixedString));
   qt_ns.addConstant("MatchCaseSensitive",       new QoreBigIntNode(Qt::MatchCaseSensitive));
   qt_ns.addConstant("MatchWrap",                new QoreBigIntNode(Qt::MatchWrap));
   qt_ns.addConstant("MatchRecursive",           new QoreBigIntNode(Qt::MatchRecursive));

   // ItemDataRole enum
   qt_ns.addConstant("DisplayRole",              new QoreBigIntNode(Qt::DisplayRole));
   qt_ns.addConstant("DecorationRole",           new QoreBigIntNode(Qt::DecorationRole));
   qt_ns.addConstant("EditRole",                 new QoreBigIntNode(Qt::EditRole));
   qt_ns.addConstant("ToolTipRole",              new QoreBigIntNode(Qt::ToolTipRole));
   qt_ns.addConstant("StatusTipRole",            new QoreBigIntNode(Qt::StatusTipRole));
   qt_ns.addConstant("WhatsThisRole",            new QoreBigIntNode(Qt::WhatsThisRole));
   qt_ns.addConstant("FontRole",                 new QoreBigIntNode(Qt::FontRole));
   qt_ns.addConstant("TextAlignmentRole",        new QoreBigIntNode(Qt::TextAlignmentRole));
   qt_ns.addConstant("BackgroundColorRole",      new QoreBigIntNode(Qt::BackgroundColorRole));
   qt_ns.addConstant("BackgroundRole",           new QoreBigIntNode(Qt::BackgroundRole));
   qt_ns.addConstant("TextColorRole",            new QoreBigIntNode(Qt::TextColorRole));
   qt_ns.addConstant("ForegroundRole",           new QoreBigIntNode(Qt::ForegroundRole));
   qt_ns.addConstant("CheckStateRole",           new QoreBigIntNode(Qt::CheckStateRole));
   qt_ns.addConstant("AccessibleTextRole",       new QoreBigIntNode(Qt::AccessibleTextRole));
   qt_ns.addConstant("AccessibleDescriptionRole", new QoreBigIntNode(Qt::AccessibleDescriptionRole));
   qt_ns.addConstant("SizeHintRole",             new QoreBigIntNode(Qt::SizeHintRole));
   qt_ns.addConstant("UserRole",                 new QoreBigIntNode(Qt::UserRole));

   // ItemFlag enum
   qt_ns.addConstant("ItemIsSelectable",         new QoreBigIntNode(Qt::ItemIsSelectable));
   qt_ns.addConstant("ItemIsEditable",           new QoreBigIntNode(Qt::ItemIsEditable));
   qt_ns.addConstant("ItemIsDragEnabled",        new QoreBigIntNode(Qt::ItemIsDragEnabled));
   qt_ns.addConstant("ItemIsDropEnabled",        new QoreBigIntNode(Qt::ItemIsDropEnabled));
   qt_ns.addConstant("ItemIsUserCheckable",      new QoreBigIntNode(Qt::ItemIsUserCheckable));
   qt_ns.addConstant("ItemIsEnabled",            new QoreBigIntNode(Qt::ItemIsEnabled));
   qt_ns.addConstant("ItemIsTristate",           new QoreBigIntNode(Qt::ItemIsTristate));
	
   // AspectRatioMode enum
   qt_ns.addConstant("IgnoreAspectRatio",        new QoreBigIntNode(Qt::IgnoreAspectRatio));
   qt_ns.addConstant("KeepAspectRatio",          new QoreBigIntNode(Qt::KeepAspectRatio));
   qt_ns.addConstant("KeepAspectRatioByExpanding", new QoreBigIntNode(Qt::KeepAspectRatioByExpanding));

   // TextFormat enum
   qt_ns.addConstant("PlainText",                new QoreBigIntNode(Qt::PlainText));
   qt_ns.addConstant("RichText",                 new QoreBigIntNode(Qt::RichText));
   qt_ns.addConstant("AutoText",                 new QoreBigIntNode(Qt::AutoText));
   qt_ns.addConstant("LogText",                  new QoreBigIntNode(Qt::LogText));

   // CursorShape enum
   qt_ns.addConstant("ArrowCursor",              new QoreBigIntNode(Qt::ArrowCursor));
   qt_ns.addConstant("UpArrowCursor",            new QoreBigIntNode(Qt::UpArrowCursor));
   qt_ns.addConstant("CrossCursor",              new QoreBigIntNode(Qt::CrossCursor));
   qt_ns.addConstant("WaitCursor",               new QoreBigIntNode(Qt::WaitCursor));
   qt_ns.addConstant("IBeamCursor",              new QoreBigIntNode(Qt::IBeamCursor));
   qt_ns.addConstant("SizeVerCursor",            new QoreBigIntNode(Qt::SizeVerCursor));
   qt_ns.addConstant("SizeHorCursor",            new QoreBigIntNode(Qt::SizeHorCursor));
   qt_ns.addConstant("SizeBDiagCursor",          new QoreBigIntNode(Qt::SizeBDiagCursor));
   qt_ns.addConstant("SizeFDiagCursor",          new QoreBigIntNode(Qt::SizeFDiagCursor));
   qt_ns.addConstant("SizeAllCursor",            new QoreBigIntNode(Qt::SizeAllCursor));
   qt_ns.addConstant("BlankCursor",              new QoreBigIntNode(Qt::BlankCursor));
   qt_ns.addConstant("SplitVCursor",             new QoreBigIntNode(Qt::SplitVCursor));
   qt_ns.addConstant("SplitHCursor",             new QoreBigIntNode(Qt::SplitHCursor));
   qt_ns.addConstant("PointingHandCursor",       new QoreBigIntNode(Qt::PointingHandCursor));
   qt_ns.addConstant("ForbiddenCursor",          new QoreBigIntNode(Qt::ForbiddenCursor));
   qt_ns.addConstant("WhatsThisCursor",          new QoreBigIntNode(Qt::WhatsThisCursor));
   qt_ns.addConstant("BusyCursor",               new QoreBigIntNode(Qt::BusyCursor));
   qt_ns.addConstant("OpenHandCursor",           new QoreBigIntNode(Qt::OpenHandCursor));
   qt_ns.addConstant("ClosedHandCursor",         new QoreBigIntNode(Qt::ClosedHandCursor));
   qt_ns.addConstant("LastCursor",               new QoreBigIntNode(Qt::LastCursor));
   qt_ns.addConstant("BitmapCursor",             new QoreBigIntNode(Qt::BitmapCursor));
   qt_ns.addConstant("CustomCursor",             new QoreBigIntNode(Qt::CustomCursor));

   // AnchorAttribute enum
   qt_ns.addConstant("AnchorName",               new QoreBigIntNode(Qt::AnchorName));
   qt_ns.addConstant("AnchorHref",               new QoreBigIntNode(Qt::AnchorHref));

   // DockWidgetArea enum
   qt_ns.addConstant("LeftDockWidgetArea",       new QoreBigIntNode(Qt::LeftDockWidgetArea));
   qt_ns.addConstant("RightDockWidgetArea",      new QoreBigIntNode(Qt::RightDockWidgetArea));
   qt_ns.addConstant("TopDockWidgetArea",        new QoreBigIntNode(Qt::TopDockWidgetArea));
   qt_ns.addConstant("BottomDockWidgetArea",     new QoreBigIntNode(Qt::BottomDockWidgetArea));
   qt_ns.addConstant("DockWidgetArea_Mask",      new QoreBigIntNode(Qt::DockWidgetArea_Mask));
   qt_ns.addConstant("AllDockWidgetAreas",       new QoreBigIntNode(Qt::AllDockWidgetAreas));
   qt_ns.addConstant("NoDockWidgetArea",         new QoreBigIntNode(Qt::NoDockWidgetArea));

   // DockWidgetAreaSizes enum
   qt_ns.addConstant("NDockWidgetAreas",         new QoreBigIntNode(Qt::NDockWidgetAreas));

   // ToolBarArea enum
   qt_ns.addConstant("LeftToolBarArea",          new QoreBigIntNode(Qt::LeftToolBarArea));
   qt_ns.addConstant("RightToolBarArea",         new QoreBigIntNode(Qt::RightToolBarArea));
   qt_ns.addConstant("TopToolBarArea",           new QoreBigIntNode(Qt::TopToolBarArea));
   qt_ns.addConstant("BottomToolBarArea",        new QoreBigIntNode(Qt::BottomToolBarArea));
   qt_ns.addConstant("ToolBarArea_Mask",         new QoreBigIntNode(Qt::ToolBarArea_Mask));
   qt_ns.addConstant("AllToolBarAreas",          new QoreBigIntNode(Qt::AllToolBarAreas));
   qt_ns.addConstant("NoToolBarArea",            new QoreBigIntNode(Qt::NoToolBarArea));

   // ToolBarSizes enum
   qt_ns.addConstant("NToolBarAreas",            new QoreBigIntNode(Qt::NToolBarAreas));

   // PenCapStyle enum
   qt_ns.addConstant("FlatCap",                  new QoreBigIntNode(Qt::FlatCap));
   qt_ns.addConstant("SquareCap",                new QoreBigIntNode(Qt::SquareCap));
   qt_ns.addConstant("RoundCap",                 new QoreBigIntNode(Qt::RoundCap));
   qt_ns.addConstant("MPenCapStyle",             new QoreBigIntNode(Qt::MPenCapStyle));

   // PenJoinStyle enum
   qt_ns.addConstant("MiterJoin",                new QoreBigIntNode(Qt::MiterJoin));
   qt_ns.addConstant("BevelJoin",                new QoreBigIntNode(Qt::BevelJoin));
   qt_ns.addConstant("RoundJoin",                new QoreBigIntNode(Qt::RoundJoin));
   qt_ns.addConstant("SvgMiterJoin",             new QoreBigIntNode(Qt::SvgMiterJoin));
   qt_ns.addConstant("MPenJoinStyle",            new QoreBigIntNode(Qt::MPenJoinStyle));

   // WidgetAttribute enum
   qt_ns.addConstant("WA_Disabled",              new QoreBigIntNode(Qt::WA_Disabled));
   qt_ns.addConstant("WA_UnderMouse",            new QoreBigIntNode(Qt::WA_UnderMouse));
   qt_ns.addConstant("WA_MouseTracking",         new QoreBigIntNode(Qt::WA_MouseTracking));
   qt_ns.addConstant("WA_ContentsPropagated",    new QoreBigIntNode(Qt::WA_ContentsPropagated));
   qt_ns.addConstant("WA_OpaquePaintEvent",      new QoreBigIntNode(Qt::WA_OpaquePaintEvent));
   qt_ns.addConstant("WA_NoBackground",          new QoreBigIntNode(Qt::WA_NoBackground));
   qt_ns.addConstant("WA_StaticContents",        new QoreBigIntNode(Qt::WA_StaticContents));
   qt_ns.addConstant("WA_LaidOut",               new QoreBigIntNode(Qt::WA_LaidOut));
   qt_ns.addConstant("WA_PaintOnScreen",         new QoreBigIntNode(Qt::WA_PaintOnScreen));
   qt_ns.addConstant("WA_NoSystemBackground",    new QoreBigIntNode(Qt::WA_NoSystemBackground));
   qt_ns.addConstant("WA_UpdatesDisabled",       new QoreBigIntNode(Qt::WA_UpdatesDisabled));
   qt_ns.addConstant("WA_Mapped",                new QoreBigIntNode(Qt::WA_Mapped));
   qt_ns.addConstant("WA_MacNoClickThrough",     new QoreBigIntNode(Qt::WA_MacNoClickThrough));
   qt_ns.addConstant("WA_PaintOutsidePaintEvent", new QoreBigIntNode(Qt::WA_PaintOutsidePaintEvent));
   qt_ns.addConstant("WA_InputMethodEnabled",    new QoreBigIntNode(Qt::WA_InputMethodEnabled));
   qt_ns.addConstant("WA_WState_Visible",        new QoreBigIntNode(Qt::WA_WState_Visible));
   qt_ns.addConstant("WA_WState_Hidden",         new QoreBigIntNode(Qt::WA_WState_Hidden));
   qt_ns.addConstant("WA_ForceDisabled",         new QoreBigIntNode(Qt::WA_ForceDisabled));
   qt_ns.addConstant("WA_KeyCompression",        new QoreBigIntNode(Qt::WA_KeyCompression));
   qt_ns.addConstant("WA_PendingMoveEvent",      new QoreBigIntNode(Qt::WA_PendingMoveEvent));
   qt_ns.addConstant("WA_PendingResizeEvent",    new QoreBigIntNode(Qt::WA_PendingResizeEvent));
   qt_ns.addConstant("WA_SetPalette",            new QoreBigIntNode(Qt::WA_SetPalette));
   qt_ns.addConstant("WA_SetFont",               new QoreBigIntNode(Qt::WA_SetFont));
   qt_ns.addConstant("WA_SetCursor",             new QoreBigIntNode(Qt::WA_SetCursor));
   qt_ns.addConstant("WA_NoChildEventsFromChildren", new QoreBigIntNode(Qt::WA_NoChildEventsFromChildren));
   qt_ns.addConstant("WA_WindowModified",        new QoreBigIntNode(Qt::WA_WindowModified));
   qt_ns.addConstant("WA_Resized",               new QoreBigIntNode(Qt::WA_Resized));
   qt_ns.addConstant("WA_Moved",                 new QoreBigIntNode(Qt::WA_Moved));
   qt_ns.addConstant("WA_PendingUpdate",         new QoreBigIntNode(Qt::WA_PendingUpdate));
   qt_ns.addConstant("WA_InvalidSize",           new QoreBigIntNode(Qt::WA_InvalidSize));
   qt_ns.addConstant("WA_MacBrushedMetal",       new QoreBigIntNode(Qt::WA_MacBrushedMetal));
   qt_ns.addConstant("WA_MacMetalStyle",         new QoreBigIntNode(Qt::WA_MacMetalStyle));
   qt_ns.addConstant("WA_CustomWhatsThis",       new QoreBigIntNode(Qt::WA_CustomWhatsThis));
   qt_ns.addConstant("WA_LayoutOnEntireRect",    new QoreBigIntNode(Qt::WA_LayoutOnEntireRect));
   qt_ns.addConstant("WA_OutsideWSRange",        new QoreBigIntNode(Qt::WA_OutsideWSRange));
   qt_ns.addConstant("WA_GrabbedShortcut",       new QoreBigIntNode(Qt::WA_GrabbedShortcut));
   qt_ns.addConstant("WA_TransparentForMouseEvents", new QoreBigIntNode(Qt::WA_TransparentForMouseEvents));
   qt_ns.addConstant("WA_PaintUnclipped",        new QoreBigIntNode(Qt::WA_PaintUnclipped));
   qt_ns.addConstant("WA_SetWindowIcon",         new QoreBigIntNode(Qt::WA_SetWindowIcon));
   qt_ns.addConstant("WA_NoMouseReplay",         new QoreBigIntNode(Qt::WA_NoMouseReplay));
   qt_ns.addConstant("WA_DeleteOnClose",         new QoreBigIntNode(Qt::WA_DeleteOnClose));
   qt_ns.addConstant("WA_RightToLeft",           new QoreBigIntNode(Qt::WA_RightToLeft));
   qt_ns.addConstant("WA_SetLayoutDirection",    new QoreBigIntNode(Qt::WA_SetLayoutDirection));
   qt_ns.addConstant("WA_NoChildEventsForParent", new QoreBigIntNode(Qt::WA_NoChildEventsForParent));
   qt_ns.addConstant("WA_ForceUpdatesDisabled",  new QoreBigIntNode(Qt::WA_ForceUpdatesDisabled));
   qt_ns.addConstant("WA_WState_Created",        new QoreBigIntNode(Qt::WA_WState_Created));
   qt_ns.addConstant("WA_WState_CompressKeys",   new QoreBigIntNode(Qt::WA_WState_CompressKeys));
   qt_ns.addConstant("WA_WState_InPaintEvent",   new QoreBigIntNode(Qt::WA_WState_InPaintEvent));
   qt_ns.addConstant("WA_WState_Reparented",     new QoreBigIntNode(Qt::WA_WState_Reparented));
   qt_ns.addConstant("WA_WState_ConfigPending",  new QoreBigIntNode(Qt::WA_WState_ConfigPending));
   qt_ns.addConstant("WA_WState_Polished",       new QoreBigIntNode(Qt::WA_WState_Polished));
   qt_ns.addConstant("WA_WState_DND",            new QoreBigIntNode(Qt::WA_WState_DND));
   qt_ns.addConstant("WA_WState_OwnSizePolicy",  new QoreBigIntNode(Qt::WA_WState_OwnSizePolicy));
   qt_ns.addConstant("WA_WState_ExplicitShowHide", new QoreBigIntNode(Qt::WA_WState_ExplicitShowHide));
   qt_ns.addConstant("WA_ShowModal",             new QoreBigIntNode(Qt::WA_ShowModal));
   qt_ns.addConstant("WA_MouseNoMask",           new QoreBigIntNode(Qt::WA_MouseNoMask));
   qt_ns.addConstant("WA_GroupLeader",           new QoreBigIntNode(Qt::WA_GroupLeader));
   qt_ns.addConstant("WA_NoMousePropagation",    new QoreBigIntNode(Qt::WA_NoMousePropagation));
   qt_ns.addConstant("WA_Hover",                 new QoreBigIntNode(Qt::WA_Hover));
   qt_ns.addConstant("WA_InputMethodTransparent", new QoreBigIntNode(Qt::WA_InputMethodTransparent));
   qt_ns.addConstant("WA_QuitOnClose",           new QoreBigIntNode(Qt::WA_QuitOnClose));
   qt_ns.addConstant("WA_KeyboardFocusChange",   new QoreBigIntNode(Qt::WA_KeyboardFocusChange));
   qt_ns.addConstant("WA_AcceptDrops",           new QoreBigIntNode(Qt::WA_AcceptDrops));
   qt_ns.addConstant("WA_DropSiteRegistered",    new QoreBigIntNode(Qt::WA_DropSiteRegistered));
   qt_ns.addConstant("WA_ForceAcceptDrops",      new QoreBigIntNode(Qt::WA_ForceAcceptDrops));
   qt_ns.addConstant("WA_WindowPropagation",     new QoreBigIntNode(Qt::WA_WindowPropagation));
   qt_ns.addConstant("WA_NoX11EventCompression", new QoreBigIntNode(Qt::WA_NoX11EventCompression));
   qt_ns.addConstant("WA_TintedBackground",      new QoreBigIntNode(Qt::WA_TintedBackground));
   qt_ns.addConstant("WA_X11OpenGLOverlay",      new QoreBigIntNode(Qt::WA_X11OpenGLOverlay));
   qt_ns.addConstant("WA_AlwaysShowToolTips",    new QoreBigIntNode(Qt::WA_AlwaysShowToolTips));
   qt_ns.addConstant("WA_MacOpaqueSizeGrip",     new QoreBigIntNode(Qt::WA_MacOpaqueSizeGrip));
   qt_ns.addConstant("WA_SetStyle",              new QoreBigIntNode(Qt::WA_SetStyle));
   qt_ns.addConstant("WA_SetLocale",             new QoreBigIntNode(Qt::WA_SetLocale));
   qt_ns.addConstant("WA_MacShowFocusRect",      new QoreBigIntNode(Qt::WA_MacShowFocusRect));
   qt_ns.addConstant("WA_MacNormalSize",         new QoreBigIntNode(Qt::WA_MacNormalSize));
   qt_ns.addConstant("WA_MacSmallSize",          new QoreBigIntNode(Qt::WA_MacSmallSize));
   qt_ns.addConstant("WA_MacMiniSize",           new QoreBigIntNode(Qt::WA_MacMiniSize));
   qt_ns.addConstant("WA_LayoutUsesWidgetRect",  new QoreBigIntNode(Qt::WA_LayoutUsesWidgetRect));
   qt_ns.addConstant("WA_StyledBackground",      new QoreBigIntNode(Qt::WA_StyledBackground));
   qt_ns.addConstant("WA_MSWindowsUseDirect3D",  new QoreBigIntNode(Qt::WA_MSWindowsUseDirect3D));
   qt_ns.addConstant("WA_CanHostQMdiSubWindowTitleBar", new QoreBigIntNode(Qt::WA_CanHostQMdiSubWindowTitleBar));
   qt_ns.addConstant("WA_MacAlwaysShowToolWindow", new QoreBigIntNode(Qt::WA_MacAlwaysShowToolWindow));
   qt_ns.addConstant("WA_StyleSheet",            new QoreBigIntNode(Qt::WA_StyleSheet));
   qt_ns.addConstant("WA_AttributeCount",        new QoreBigIntNode(Qt::WA_AttributeCount));

   // WindowType enum
   qt_ns.addConstant("Widget",                   new QoreBigIntNode(Qt::Widget));
   qt_ns.addConstant("Window",                   new QoreBigIntNode(Qt::Window));
   qt_ns.addConstant("Dialog",                   new QoreBigIntNode(Qt::Dialog));
   qt_ns.addConstant("Sheet",                    new QoreBigIntNode(Qt::Sheet));
   qt_ns.addConstant("Drawer",                   new QoreBigIntNode(Qt::Drawer));
   qt_ns.addConstant("Popup",                    new QoreBigIntNode(Qt::Popup));
   qt_ns.addConstant("Tool",                     new QoreBigIntNode(Qt::Tool));
   qt_ns.addConstant("ToolTip",                  new QoreBigIntNode(Qt::ToolTip));
   qt_ns.addConstant("SplashScreen",             new QoreBigIntNode(Qt::SplashScreen));
   qt_ns.addConstant("Desktop",                  new QoreBigIntNode(Qt::Desktop));
   qt_ns.addConstant("SubWindow",                new QoreBigIntNode(Qt::SubWindow));
   qt_ns.addConstant("WindowType_Mask",          new QoreBigIntNode(Qt::WindowType_Mask));
   qt_ns.addConstant("MSWindowsFixedSizeDialogHint", new QoreBigIntNode(Qt::MSWindowsFixedSizeDialogHint));
   qt_ns.addConstant("MSWindowsOwnDC",           new QoreBigIntNode(Qt::MSWindowsOwnDC));
   qt_ns.addConstant("X11BypassWindowManagerHint", new QoreBigIntNode(Qt::X11BypassWindowManagerHint));
   qt_ns.addConstant("FramelessWindowHint",      new QoreBigIntNode(Qt::FramelessWindowHint));
   qt_ns.addConstant("WindowTitleHint",          new QoreBigIntNode(Qt::WindowTitleHint));
   qt_ns.addConstant("WindowSystemMenuHint",     new QoreBigIntNode(Qt::WindowSystemMenuHint));
   qt_ns.addConstant("WindowMinimizeButtonHint", new QoreBigIntNode(Qt::WindowMinimizeButtonHint));
   qt_ns.addConstant("WindowMaximizeButtonHint", new QoreBigIntNode(Qt::WindowMaximizeButtonHint));
   qt_ns.addConstant("WindowMinMaxButtonsHint",  new QoreBigIntNode(Qt::WindowMinMaxButtonsHint));
   qt_ns.addConstant("WindowContextHelpButtonHint", new QoreBigIntNode(Qt::WindowContextHelpButtonHint));
   qt_ns.addConstant("WindowShadeButtonHint",    new QoreBigIntNode(Qt::WindowShadeButtonHint));
   qt_ns.addConstant("WindowStaysOnTopHint",     new QoreBigIntNode(Qt::WindowStaysOnTopHint));
   qt_ns.addConstant("CustomizeWindowHint",      new QoreBigIntNode(Qt::CustomizeWindowHint));

   // FocusPolicy enum
   qt_ns.addConstant("NoFocus",                  new QoreBigIntNode(Qt::NoFocus));
   qt_ns.addConstant("TabFocus",                 new QoreBigIntNode(Qt::TabFocus));
   qt_ns.addConstant("ClickFocus",               new QoreBigIntNode(Qt::ClickFocus));
   qt_ns.addConstant("StrongFocus",              new QoreBigIntNode(Qt::StrongFocus));
   qt_ns.addConstant("WheelFocus",               new QoreBigIntNode(Qt::WheelFocus));

   // ConnectionType enum
   qt_ns.addConstant("AutoConnection",           new QoreBigIntNode(Qt::AutoConnection));
   qt_ns.addConstant("DirectConnection",         new QoreBigIntNode(Qt::DirectConnection));
   qt_ns.addConstant("QueuedConnection",         new QoreBigIntNode(Qt::QueuedConnection));
   qt_ns.addConstant("AutoCompatConnection",     new QoreBigIntNode(Qt::AutoCompatConnection));
   qt_ns.addConstant("BlockingQueuedConnection", new QoreBigIntNode(Qt::BlockingQueuedConnection));

   // DateFormat enum
   qt_ns.addConstant("TextDate",                 new QoreBigIntNode(Qt::TextDate));
   qt_ns.addConstant("ISODate",                  new QoreBigIntNode(Qt::ISODate));
   qt_ns.addConstant("SystemLocaleDate",         new QoreBigIntNode(Qt::SystemLocaleDate));
   qt_ns.addConstant("LocalDate",                new QoreBigIntNode(Qt::LocalDate));
   qt_ns.addConstant("LocaleDate",               new QoreBigIntNode(Qt::LocaleDate));

   // TimeSpec enum
   qt_ns.addConstant("LocalTime",                new QoreBigIntNode(Qt::LocalTime));
   qt_ns.addConstant("UTC",                      new QoreBigIntNode(Qt::UTC));

   // ScrollBarPolicy enum
   qt_ns.addConstant("ScrollBarAsNeeded",        new QoreBigIntNode(Qt::ScrollBarAsNeeded));
   qt_ns.addConstant("ScrollBarAlwaysOff",       new QoreBigIntNode(Qt::ScrollBarAlwaysOff));
   qt_ns.addConstant("ScrollBarAlwaysOn",        new QoreBigIntNode(Qt::ScrollBarAlwaysOn));

   // CaseSensitivity enum
   qt_ns.addConstant("CaseInsensitive",          new QoreBigIntNode(Qt::CaseInsensitive));
   qt_ns.addConstant("CaseSensitive",            new QoreBigIntNode(Qt::CaseSensitive));

   // Corner enum
   qt_ns.addConstant("TopLeftCorner",            new QoreBigIntNode(Qt::TopLeftCorner));
   qt_ns.addConstant("TopRightCorner",           new QoreBigIntNode(Qt::TopRightCorner));
   qt_ns.addConstant("BottomLeftCorner",         new QoreBigIntNode(Qt::BottomLeftCorner));
   qt_ns.addConstant("BottomRightCorner",        new QoreBigIntNode(Qt::BottomRightCorner));

   // ShortcutContext enum
   qt_ns.addConstant("WidgetShortcut",           new QoreBigIntNode(Qt::WidgetShortcut));
   qt_ns.addConstant("WindowShortcut",           new QoreBigIntNode(Qt::WindowShortcut));
   qt_ns.addConstant("ApplicationShortcut",      new QoreBigIntNode(Qt::ApplicationShortcut));

   // FillRule enum
   qt_ns.addConstant("OddEvenFill",              new QoreBigIntNode(Qt::OddEvenFill));
   qt_ns.addConstant("WindingFill",              new QoreBigIntNode(Qt::WindingFill));

   // MaskMode enum
   qt_ns.addConstant("MaskInColor",              new QoreBigIntNode(Qt::MaskInColor));
   qt_ns.addConstant("MaskOutColor",             new QoreBigIntNode(Qt::MaskOutColor));

   // ClipOperation enum
   qt_ns.addConstant("NoClip",                   new QoreBigIntNode(Qt::NoClip));
   qt_ns.addConstant("ReplaceClip",              new QoreBigIntNode(Qt::ReplaceClip));
   qt_ns.addConstant("IntersectClip",            new QoreBigIntNode(Qt::IntersectClip));
   qt_ns.addConstant("UniteClip",                new QoreBigIntNode(Qt::UniteClip));

   // LayoutDirection enum
   qt_ns.addConstant("LeftToRight",              new QoreBigIntNode(Qt::LeftToRight));
   qt_ns.addConstant("RightToLeft",              new QoreBigIntNode(Qt::RightToLeft));

   // ItemSelectionMode
   qt_ns.addConstant("ContainsItemShape",        new QoreBigIntNode(Qt::ContainsItemShape));
   qt_ns.addConstant("IntersectsItemShape",      new QoreBigIntNode(Qt::IntersectsItemShape));
   qt_ns.addConstant("ContainsItemBoundingRect", new QoreBigIntNode(Qt::ContainsItemBoundingRect));
   qt_ns.addConstant("IntersectsItemBoundingRect", new QoreBigIntNode(Qt::IntersectsItemBoundingRect));

   // TransformationMode enum
   qt_ns.addConstant("FastTransformation",       new QoreBigIntNode(Qt::FastTransformation));
   qt_ns.addConstant("SmoothTransformation",     new QoreBigIntNode(Qt::SmoothTransformation));

   // Axis enum
   qt_ns.addConstant("XAxis",                    new QoreBigIntNode(Qt::XAxis));
   qt_ns.addConstant("YAxis",                    new QoreBigIntNode(Qt::YAxis));
   qt_ns.addConstant("ZAxis",                    new QoreBigIntNode(Qt::ZAxis));

   // WindowModality enum
   qt_ns.addConstant("NonModal",                 new QoreBigIntNode(Qt::NonModal));
   qt_ns.addConstant("WindowModal",              new QoreBigIntNode(Qt::WindowModal));
   qt_ns.addConstant("ApplicationModal",         new QoreBigIntNode(Qt::ApplicationModal));   
}
